"""initial catalog schema (doc 04 §2.4)

Revision ID: bcdabfe0f95c
Revises: 
Create Date: 2026-06-13 16:22:51.680299
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bcdabfe0f95c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_root', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('render_type', sa.Text(), nullable=False),
    sa.Column('visible', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('style_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spatial_frame',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('horizontal_crs', sa.Text(), nullable=True),
    sa.Column('vertical_datum', sa.Text(), nullable=True),
    sa.Column('anchor_json', sa.Text(), nullable=True),
    sa.Column('rotation_deg', sa.Float(), nullable=False),
    sa.Column('axis_convention', sa.Text(), nullable=False),
    sa.Column('length_unit', sa.Text(), nullable=False),
    sa.Column('roi_json', sa.Text(), nullable=False),
    sa.Column('depth_range_json', sa.Text(), nullable=False),
    sa.Column('surface_model', sa.Text(), nullable=True),
    sa.Column('frame_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('camera_json', sa.Text(), nullable=True),
    sa.Column('layer_set_json', sa.Text(), nullable=True),
    sa.Column('time_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_kind', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('process', sa.Text(), nullable=False),
    sa.Column('process_version', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('source_crs', sa.Text(), nullable=True),
    sa.Column('source_unit', sa.Text(), nullable=True),
    sa.Column('raw_file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('submethod', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('extent_json', sa.Text(), nullable=False),
    sa.Column('time_extent_json', sa.Text(), nullable=True),
    sa.Column('spatial_frame_id', sa.String(), nullable=False),
    sa.Column('origin_crs', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('version_root_id', sa.String(), nullable=False),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('version_parent_id', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.ForeignKeyConstraint(['spatial_frame_id'], ['spatial_frame.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance_inputs',
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('input_kind', sa.Text(), nullable=False),
    sa.Column('input_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provenance_id', 'input_kind', 'input_id')
    )
    op.create_table('features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('feature_type', sa.Text(), nullable=False),
    sa.Column('store_uri', sa.Text(), nullable=True),
    sa.Column('store_format', sa.Text(), nullable=False),
    sa.Column('geometry_wkb', sa.BLOB(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('has_time', sa.Integer(), nullable=False),
    sa.Column('props_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fused_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('grid_type', sa.Text(), nullable=False),
    sa.Column('store_uri', sa.Text(), nullable=False),
    sa.Column('store_format', sa.Text(), nullable=False),
    sa.Column('shape_json', sa.Text(), nullable=False),
    sa.Column('spacing_json', sa.Text(), nullable=False),
    sa.Column('origin_json', sa.Text(), nullable=False),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('has_time', sa.Integer(), nullable=False),
    sa.Column('time_extent_json', sa.Text(), nullable=True),
    sa.Column('pyramid_levels', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('geometry_kind', sa.Text(), nullable=False),
    sa.Column('primary_property', sa.Text(), nullable=True),
    sa.Column('geometry_wkb', sa.BLOB(), nullable=True),
    sa.Column('values_uri', sa.Text(), nullable=True),
    sa.Column('values_json', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('acquired_at', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('property', sa.Text(), nullable=False),
    sa.Column('canonical_unit', sa.Text(), nullable=False),
    sa.Column('support', sa.Text(), nullable=False),
    sa.Column('store_uri', sa.Text(), nullable=False),
    sa.Column('store_format', sa.Text(), nullable=False),
    sa.Column('shape_json', sa.Text(), nullable=False),
    sa.Column('spacing_json', sa.Text(), nullable=True),
    sa.Column('origin_json', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('has_time', sa.Integer(), nullable=False),
    sa.Column('pyramid_levels', sa.Integer(), nullable=False),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('uncertainty_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fused_layers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fused_model_id', sa.String(), nullable=False),
    sa.Column('source_property_model_id', sa.String(), nullable=False),
    sa.Column('source_version', sa.Text(), nullable=False),
    sa.Column('property', sa.Text(), nullable=False),
    sa.Column('resample_op_json', sa.Text(), nullable=False),
    sa.Column('sigma_array', sa.Text(), nullable=True),
    sa.Column('valid_mask', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fused_model_id'], ['fused_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_property_model_id'], ['property_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fused_layers')
    op.drop_table('property_models')
    op.drop_table('observations')
    op.drop_table('fused_models')
    op.drop_table('features')
    op.drop_table('provenance_inputs')
    op.drop_table('datasets')
    op.drop_table('provenance')
    op.drop_table('views')
    op.drop_table('spatial_frame')
    op.drop_table('raw_files')
    op.drop_table('layers')
    op.drop_table('jobs')
    op.drop_table('projects')
    # ### end Alembic commands ###
