# Geothermal Underground Simulator — developer command reference.
# Run `make` or `make help` to list targets.
#
# Layout:  backend/ (FastAPI + Python, uv venv)   frontend/ (React+TS+Vite)
# Most backend targets use the project venv directly (backend/.venv) so they don't
# re-sync; run `make setup` once first.

# ---- config ---------------------------------------------------------------------
# Absolute paths (via $(CURDIR)) so they survive the `cd` inside each recipe.
BACKEND      := backend
FRONTEND     := frontend
VENV         := $(CURDIR)/$(BACKEND)/.venv
PY           := $(VENV)/bin/python
RUFF         := $(VENV)/bin/ruff
PYTEST       := $(PY) -m pytest
UV           := uv
NPM          := npm
DEV_DATA     := .devdata           # persistent catalog + storage for `make demo`
HOST         ?= 127.0.0.1
PORT         ?= 8000
SCENARIO     ?= great-basin-v1     # override: make scenario SCENARIO=unit-cube-v1

.DEFAULT_GOAL := help

# =================================================================================
# Setup
# =================================================================================
.PHONY: setup
setup: install-backend install-frontend ## Install everything (backend venv + deps, frontend deps)

.PHONY: install-backend
install-backend: ## Create the backend venv and install core + dev + ingest + fusion deps
	cd $(BACKEND) && $(UV) venv --python 3.12
	cd $(BACKEND) && $(UV) pip install -e ".[dev,ingest,fusion]"

.PHONY: install-backend-full
install-backend-full: ## Backend deps INCLUDING heavy solvers (T1 forward, GemPy, SimPEG/PyGIMLi, Postgres)
	cd $(BACKEND) && $(UV) pip install -e ".[dev,ingest,fusion,forward-t1,geomodel,inversion,postgres]"

.PHONY: install-frontend
install-frontend: ## Install frontend npm dependencies
	cd $(FRONTEND) && $(NPM) install

# =================================================================================
# Infra (optional — Postgres + PostGIS + Redis via Docker; SQLite/inline is the default)
# =================================================================================
.PHONY: infra-up
infra-up: ## Start Postgres+PostGIS and Redis (docker compose)
	docker compose up -d

.PHONY: infra-down
infra-down: ## Stop the infra containers
	docker compose down

.PHONY: infra-logs
infra-logs: ## Tail the infra container logs
	docker compose logs -f

# =================================================================================
# Backend — test / lint / format
# =================================================================================
.PHONY: test test-backend
test test-backend: ## Run the backend test suite (pytest)
	cd $(BACKEND) && $(PYTEST) -q

.PHONY: test-backend-fast
test-backend-fast: ## Backend tests, stop on first failure
	cd $(BACKEND) && $(PYTEST) -x -q

.PHONY: lint
lint: ## Lint the enforced surface (ruff check geosim + scripts)
	cd $(BACKEND) && $(RUFF) check geosim scripts

.PHONY: lint-all
lint-all: ## Lint everything including tests (test files carry some known drift)
	cd $(BACKEND) && $(RUFF) check geosim scripts tests

.PHONY: format
format: ## Auto-fix lint + format the backend (ruff)
	cd $(BACKEND) && $(RUFF) check --fix geosim scripts tests
	cd $(BACKEND) && $(RUFF) format geosim scripts tests

# =================================================================================
# Backend — run
# =================================================================================
.PHONY: run-backend
run-backend: ## Run the API (ephemeral: in-memory SQLite + temp storage; good for /api + mock UI)
	cd $(BACKEND) && $(VENV)/bin/uvicorn geosim.api.app:create_app --factory --host $(HOST) --port $(PORT) --reload

.PHONY: demo
demo: ## Run a PERSISTENT, seeded dev server (real data the viewer can load)
	cd $(BACKEND) && $(PY) scripts/dev_server.py --data-dir ../$(DEV_DATA) --host $(HOST) --port $(PORT)

.PHONY: demo-reseed
demo-reseed: ## Wipe the dev data dir and reseed, then serve
	cd $(BACKEND) && $(PY) scripts/dev_server.py --data-dir ../$(DEV_DATA) --host $(HOST) --port $(PORT) --reseed

.PHONY: worker
worker: ## Run an RQ background-job worker (requires Redis; queue "geosim")
	cd $(BACKEND) && $(VENV)/bin/rq worker geosim

.PHONY: migrate
migrate: ## Apply Alembic catalog migrations (set GEOSIM_DB_URL for Postgres; default SQLite)
	cd $(BACKEND)/geosim/catalog/migrations && $(VENV)/bin/alembic upgrade head

.PHONY: migration
migration: ## Create a new autogenerated Alembic migration (make migration M="message")
	cd $(BACKEND)/geosim/catalog/migrations && $(VENV)/bin/alembic revision --autogenerate -m "$(M)"

# =================================================================================
# Synthetic data generator (doc 05)
# =================================================================================
.PHONY: scenarios
scenarios: ## List the available synthetic scenarios
	cd $(BACKEND) && $(PY) -m geosim.synthgen list

.PHONY: scenario
scenario: ## Build a synthetic scenario to scenarios/<id>/ (make scenario SCENARIO=great-basin-v1)
	cd $(BACKEND) && $(PY) -m geosim.synthgen build $(SCENARIO) --out ../scenarios/$(SCENARIO)

# =================================================================================
# Frontend
# =================================================================================
.PHONY: run-frontend dev
run-frontend dev: ## Run the Vite dev server (viewer at http://localhost:5173)
	cd $(FRONTEND) && $(NPM) run dev

.PHONY: build-frontend
build-frontend: ## Production build of the frontend (tsc + vite build)
	cd $(FRONTEND) && $(NPM) run build

.PHONY: test-frontend
test-frontend: ## Run the frontend unit tests
	cd $(FRONTEND) && $(NPM) test

.PHONY: typecheck
typecheck: ## Type-check the frontend (tsc --noEmit)
	cd $(FRONTEND) && $(NPM) run typecheck

# =================================================================================
# Combined / CI
# =================================================================================
.PHONY: test-all
test-all: test-backend test-frontend ## Run backend + frontend test suites

.PHONY: check
check: lint typecheck test-all build-frontend ## Full CI gate: lint + typecheck + tests + build

.PHONY: run
run: ## Reminder: start backend and frontend in two terminals
	@echo "Terminal 1:  make demo          # seeded API on http://$(HOST):$(PORT)"
	@echo "Terminal 2:  make run-frontend   # viewer on http://localhost:5173"
	@echo "Then open the viewer; it loads the seeded project via the discovery panel."

# =================================================================================
# Housekeeping
# =================================================================================
.PHONY: clean
clean: ## Remove caches + build output + dev data (keeps venv & node_modules)
	rm -rf $(DEV_DATA) $(FRONTEND)/dist $(FRONTEND)/.test-out
	find $(BACKEND) -type d -name __pycache__ -prune -exec rm -rf {} +
	rm -rf $(BACKEND)/.pytest_cache $(BACKEND)/.ruff_cache

.PHONY: clean-all
clean-all: clean ## Also remove the venv and node_modules (full reset; rerun `make setup`)
	rm -rf $(VENV) $(FRONTEND)/node_modules

.PHONY: help
help: ## Show this help
	@echo "Geothermal Underground Simulator — make targets:"
	@echo ""
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'
	@echo ""
	@echo "Quick start:  make setup && make run"
